theme = 'hugo-book'
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'The Finest Creations: Guide'

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'dark'