name: Push to GitHub Pages on push to main
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Hugo Deploy GitHub Pages
        uses: benmatselby/hugo-deploy-gh-pages@v2.1.0
        env:
          HUGO_VERSION: 0.115.1
          TARGET_REPO: https://github.com/Treeway7/tfc-minecraft-website
          TARGET_BRANCH: main
          TOKEN: ${{ secrets.TOKEN }}
          HUGO_ARGS: ''
          CNAME: Treeway7.github.io/tfc-minecraft-website